services:
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress_web
    #image: wordpress
    image: wordpress:5.1.1-fpm-alpine
    volumes:
      - /mnt/ebs/wordpress:/var/www/html
    networks:
      - web_cont_net
    restart: unless-stopped
    env_file: .env
    environment:
       WORDPRESS_DB_HOST: mariadb:3306
       WORDPRESS_DB_USER: $MYSQL_USER
       WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
       WORDPRESS_DB_NAME: cloud_db

  mariadb:
      container_name: wordpress_db
      image: mariadb
      restart: unless-stopped
      env_file: .env
      environment:
        - MYSQL_DATABASE=cloud_db
      volumes:
        - /mnt/ebs/db:/var/lib/mysql
      networks:
        - web_cont_net

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/ebs/wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - web_cont_net

 # certbot:
 #     depends_on:
 #       - webserver
 #     image: certbot/certbot
 #     container_name: certbot
 #     volumes:
 #       - certbot-etc:/etc/letsencrypt
 #       - /mnt/ebs/wordpress:/var/www/html
 #     command: certonly --webroot --webroot-path=/var/www/html --email suhansaha@gmail.com --agree-tos --no-eff-email --force-renewal -d formillennial.com -d www.formillennial.com

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      env_file: .env
      environment:
        PMA_HOST: mariadb:3306 # Connects to the 'db' service
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD # Or PMA_ARBITRARY=1 for external connection
      depends_on:
        - mariadb
      networks:
        - web_cont_net


volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  web_cont_net:
    driver: bridge

